# A first workflow to play with editor
name: My First Workflow
on:
  push:
     branches: 
       - main
  workflow_dispatch:
jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Hello world from ${{ github.actor }}."
         echo "Current branch is '${{ github.ref }}'."
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - run: tree
